const InventorySummaryResponse = [
  {
    typeID: 1,
    typeName: 'Voltmeter',
    inventoryAmount: 20,
    reservationAmount: 5,
  },
  {
    typeID: 2,
    typeName: 'Thermometer',
    inventoryAmount: 15,
    reservationAmount: 5,
  },
  {
    typeID: 3,
    typeName: 'Barometer',
    inventoryAmount: 12,
    reservationAmount: 0,
  },
  {
    typeID: 4,
    typeName: 'Ammeter',
    inventory: 8,
    reservationAmount: 2,
  },
  {
    typeID: 5,
    typeName: 'Multimeter',
    inventory: 5,
    reservationAmount: 8,
  },
  {
    typeID: 6,
    typeName: 'Hydrometer',
    inventoryAmount: 10,
    reservationAmount: 3,
  },
  {
    typeID: 7,
    typeName: 'Oscilloscope',
    inventoryAmount: 18,
    reservationAmount: 6,
  },
  {
    typeID: 8,
    typeName: 'Spectrophotometer',
    inventoryAmount: 22,
    reservationAmount: 1,
  },
  {
    typeID: 9,
    typeName: 'Manometer',
    inventoryAmount: 7,
    reservationAmount: 0,
  },
  {
    typeID: 10,
    typeName: 'Luxmeter',
    inventoryAmount: 14,
    reservationAmount: 4,
  },
];

const AllReservationsResponse = [
  {
    reservationID: 1,
    renterName: 'Kim Yoo',
    startDate: '12/06/2023',
    endDate: '12/08/2023',
    status: 'Approved',
    reserveAmount: 2,
  },
  {
    reservationID: 3,
    renterName: 'Jay Jackson',
    startDate: '12/05/2023',
    endDate: '12/09/2023',
    status: 'Approved',
    reserveAmount: 1,
  },
  {
    reservationID: 4,
    renterName: 'James Walker',
    startDate: '12/09/2023',
    endDate: '12/12/2023',
    status: 'Approved',
    reserveAmount: 12,
  },
  {
    reservationID: 5,
    renterName: 'Maria Garcia',
    startDate: '12/15/2023',
    endDate: '12/18/2023',
    status: 'Requested',
    reserveAmount: 1,
  },
  {
    reservationID: 6,
    renterName: 'John Doe',
    startDate: '12/10/2023',
    endDate: '12/14/2023',
    status: 'Requested',
    reserveAmount: 2,
  },
  {
    reservationID: 7,
    renterName: 'Emily Wilson',
    startDate: '12/20/2023',
    endDate: '12/22/2023',
    status: 'Requested',
    reserveAmount: 8,
  },
  {
    reservationID: 8,
    renterName: 'Daniel Smith',
    startDate: '12/25/2023',
    endDate: '12/27/2023',
    status: 'Approved',
    reserveAmount: 2,
  },
  {
    reservationID: 9,
    renterName: 'Amanda Lee',
    startDate: '12/28/2023',
    endDate: '12/30/2023',
    status: 'Approved',
    reserveAmount: 6,
  },
  {
    reservationID: 10,
    renterName: 'Michael Brown',
    startDate: '12/17/2023',
    endDate: '12/20/2023',
    status: 'Approved',
    reserveAmount: 2,
  },
  {
    reservationID: 11,
    renterName: 'Sophia Johnson',
    startDate: '12/23/2023',
    endDate: '12/26/2023',
    status: 'Requested',
    reserveAmount: 7,
  },
  {
    reservationID: 12,
    renterName: 'Robert White',
    startDate: '12/28/2023',
    endDate: '12/31/2023',
    status: 'Requested',
    reserveAmount: 2,
  },
  {
    reservationID: 13,
    renterName: 'Emma Harris',
    startDate: '12/10/2023',
    endDate: '12/15/2023',
    status: 'Approved',
    reserveAmount: 3,
  },
];

export { InventorySummaryResponse, AllReservationsResponse };
